global:
  scrape_interval: 15s # Interval to pull metrics from targets
  evaluation_interval: 15s # Interval to evaluate alerting/recording rules
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
      - targets:
          - "alertmanager:9093"

rule_files:
  - /config/rules/*.yml

scrape_configs:
# - job_name: "my-example"
#   static_configs:
#     - targets:
#       - "metrics.my-example.s.redhost.be"
