global:
  scrape_interval: 15s # Interval to pull metrics from targets
  evaluation_interval: 15s # Interval to evaluate alerting/recording rules
  scrape_timeout: 10s

storage:
  tsdb:
    retention_time: 30d

alerting:
  alertmanagers:
    - static_configs:
      - targets:
          - "alertmanager:9093"

rule_files:
  - /config/rules/*.yml

scrape_configs:
  # Regular metrics via node-exporter
  - job_name: "server-metrics"
    static_configs:
      - targets:
        # - "metrics.my-example.s.redhost.be"

  # Website HTTPs uptime via blackbox-exporter
  - job_name: "website-uptime"
    metrics_path: /probe
    scrape_interval: 1m
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        # - https://my.example.com/
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: blackbox:9115

  # JSON API uptime via blackbox-exporter
  - job_name: "json-api-uptime"
    metrics_path: /probe
    scrape_interval: 1m
    params:
      module: [http_2xx_json]
    static_configs:
      - targets:
        # - https://my.example.com/
    relabel_configs:
      - source_labels: [__address__]
        regex: (.*)(:80)?
        target_label: __param_target
        replacement: ${1}
      - source_labels: [__param_target]
        regex: (.*)
        target_label: instance
        replacement: ${1}
      - source_labels: []
        regex: .*
        target_label: __address__
        replacement: blackbox:9115

  # Proxmox cluster metrics via pve-exporter
  - job_name: "pve"
    metrics_path: /pve
    static_configs:
      - targets:
        # - my-example.com # Entire Proxmox cluster is monitored via single node
    params:
      module: [default]
      cluster: ["1"]
      node: ["1"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: pve-exporter:9221
